baseURL = 'https://go.aznotes.me/'
languageCode = 'en-us'
title = 'Aaron Notes'
theme = 'PaperMod'

[params.homeInfoParams]
Title = "Welcome to my notes :)"
Content = "You can know me more here."

[menus]
  [[menus.main]]
    name = 'Search'
    pageRef = '/search'
    weight = 1

[params]
defaultTheme = "auto"
