baseURL = 'https://go.aznotes.me/'
languageCode = 'en-us'
title = 'Aaron Notes'
theme = 'PaperMod'

[params.homeInfoParams]
Title = "Welcome :)"
Content = "This is my personal notes. I write about my learning and experience. I hope you find it useful."

[[params.socialIcons]]
name = "github"
url = "https://github.com/"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/"

[[params.socialIcons]]
name = "x"
url = "https://x.com/"


[menus]
  [[menus.main]]
    name = 'Search'
    pageRef = '/search'
    weight = 1

[params]
defaultTheme = "auto"
ShowBreadCrumbs = true
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true